 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic_sensor.c
 *
 * Description: Source file for the Ultrasonic Sensor driver
 *
 * Author: Peter Nabil
 *
 *******************************************************************************/

#include <util/delay.h>
#include "ultrasonic_sensor.h"
#include "gpio.h"
#include "icu.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_flag = 0; /* This flag is set when the high time is calculated */
uint8 g_edgeCount = 0; /* Variable to count the edges */
uint16 g_timeHigh = 0; /* This is the time in which the signal travels from HC-SR04 to object and returns to the module HC-SR-04 again */

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description :
 * Function responsible for initializing the ICU driver, setup the ICU call back function
 * and setup the direction for the trigger pin as output pin.
 */
void Ultrasonic_init(void)
{
	/* The TRIGGER_PIN is the pin responsible for sending the Trigger pulse to the Ultrasonic Sensor */
	GPIO_setupPinDirection(TRIGGER_PORT, TRIGGER_PIN, PIN_OUTPUT);
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);

	/* Configure the ICU Driver with F_CPU/8 and wait for the RISING edge at the beginning */
	ICU_ConfigType ICU_Configurations = {F_CPU_8, RISING};
	ICU_init(&ICU_Configurations);

	/* Ultrasonic_edgeProcessing() is the CallBack Function called by the ICU Driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
}

/*
 * Description :
 * Function responsible for sending the Trigger pulse to the Ultrasonic Sensor.
 */
void Ultrasonic_Trigger(void)
{
	/* Send a 20 microseconds pulse to the Ultrasonic Sensor through the TRIGGER_PIN */
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(20);
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description :
 * Function responsible for sending the trigger pulse by using Ultrasonic_Trigger() function
 * and start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distnace;
	Ultrasonic_Trigger(); /* Send a 20 microseconds pulse to the Ultrasonic Sensor through the TRIGGER_PIN */
	while(g_flag != 1); /* Wait till the CallBack Function (Ultrasonic_edgeProcessing()) calculate the high time (pulse time) generated by the Ultrasonic Sensor*/

	/* (Distance = 0.017 * Timer value) as we have selected an internal 8MHz oscillator frequency for ATmega32
	 * with Prescaler F_CPU/8 for timer frequency then time to execute 1 instruction is 1 us*/
	distnace = (g_timeHigh / 58);
	/*distnace = ((float)g_timeHigh * 0.017);*/
	/*distnace = (17 * (uint32)g_timeHigh / 1000);*/

	return distnace;
}

/*
 * Description :
 * This is the call back function called by the ICU driver, It is used to calculate
 * the high time (pulse time) generated by the Ultrasonic Sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	g_flag = 0; /* Clear the g_flag to not execute the distance measurement in the Ultrasonic_readDistance Function */
	if(g_edgeCount == 1) /* Fisrt Edge (RISING) */
	{
		ICU_clearTimerValue(); /* Clear the timer counter register to start measurements from the first detected RISING Edge */
		ICU_setEdgeDetectionType(FALLING); /* Wait for the FALLING Edge */
	}
	else if(g_edgeCount == 2) /* Second Edge (FALLING) */
	{
		g_timeHigh = ICU_getInputCaptureValue(); /* Store the High time value */
		ICU_setEdgeDetectionType(RISING); /* Wait for the RISING Edge */
		g_edgeCount = 0; /* Clear the g_edgeCount to calculate a new high time generated by the Ultrasonic Sensor */
		g_flag = 1; /* Set g_flag to execute the distance measurement in the Ultrasonic_readDistance Function */
	}
}

